import "./globals.css";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 ">
        {/* ✅ Navbar */}
        <nav className="sticky top-2 z-50 mx-6">
          <div
            className="max-w-6xl mx-auto flex justify-between items-center px-6 py-3 
                          bg-gray-00 text-black rounded-full shadow-md"
          >
            {/* Logo / Name */}
            <Link href="/" className="text-xl font-bold">
              Shalom<span className="text-blue-500">.dev</span>
            </Link>

            {/* Nav Links */}
            <div className="flex gap-6">
              <a href="#about" className="hover:text-blue-400 transition">
                About
              </a>
              <a href="#skills" className="hover:text-blue-400 transition">
                Skills
              </a>
              <a href="#projects" className="hover:text-blue-400 transition">
                Projects
              </a>
              <a href="#contact" className="hover:text-blue-400 transition">
                Contact
              </a>
            </div>
          </div>
        </nav>

        {/* Page Content */}
        {children}
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// <nav className="flex justify-center gap-6 py-4 bg-gray-900 text-white sticky top-0">
//   <a href="#about" className="hover:text-blue-400">About</a>
//   <a href="#projects" className="hover:text-blue-400">Projects</a>
//   <a href="#contact" className="hover:text-blue-400">Contact</a>
// </nav>

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
